[package]
name = "moonbeam-precompile-common"
authors = { workspace = true }
description = "Precompile common logic"
edition = "2021"
version = "0.1.0"

[dependencies]

[dev-dependencies]

[features]
default = ["std"]
std = []
